version: "3"

services:
  postgres:
    container_name: postgres
    image: cimg/postgres:15.1-postgis
    command: postgres -c 'max_connections=200'
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
